// the bellow code was generated by github copilot 🤣
export function fileTypeFromBuffer(fileBuffer: Buffer) {
  let fileType = '';
  if (
    fileBuffer[0] === 0xff &&
    fileBuffer[1] === 0xd8 &&
    fileBuffer[2] === 0xff
  ) {
    fileType = 'jpeg';
  } else if (
    fileBuffer[0] === 0x47 &&
    fileBuffer[1] === 0x49 &&
    fileBuffer[2] === 0x46
  ) {
    fileType = 'gif';
  } else if (
    fileBuffer[0] === 0x89 &&
    fileBuffer[1] === 0x50 &&
    fileBuffer[2] === 0x4e &&
    fileBuffer[3] === 0x47 &&
    fileBuffer[4] === 0x0d &&
    fileBuffer[5] === 0x0a &&
    fileBuffer[6] === 0x1a &&
    fileBuffer[7] === 0x0a
  ) {
    fileType = 'png';
  } else if (
    fileBuffer[0] === 0x52 &&
    fileBuffer[1] === 0x49 &&
    fileBuffer[2] === 0x46 &&
    fileBuffer[3] === 0x46
  ) {
    fileType = 'webp';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x18 &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x69 &&
    fileBuffer[9] === 0x73 &&
    fileBuffer[10] === 0x6f &&
    fileBuffer[11] === 0x6d
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x14 &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x71 &&
    fileBuffer[9] === 0x74 &&
    fileBuffer[10] === 0x20 &&
    fileBuffer[11] === 0x20
  ) {
    fileType = 'mov';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x20 &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x6d &&
    fileBuffer[9] === 0x70 &&
    fileBuffer[10] === 0x34 &&
    fileBuffer[11] === 0x32
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x4d &&
    fileBuffer[1] === 0x34 &&
    fileBuffer[2] === 0x56
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x1c &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x6d &&
    fileBuffer[9] === 0x70 &&
    fileBuffer[10] === 0x34 &&
    fileBuffer[11] === 0x31
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x66 &&
    fileBuffer[1] === 0x74 &&
    fileBuffer[2] === 0x79 &&
    fileBuffer[3] === 0x70 &&
    fileBuffer[4] === 0x33 &&
    fileBuffer[5] === 0x67 &&
    fileBuffer[6] === 0x70 &&
    fileBuffer[7] === 0x35
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x18 &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x69 &&
    fileBuffer[9] === 0x73 &&
    fileBuffer[10] === 0x6f &&
    fileBuffer[11] === 0x32
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x14 &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x69 &&
    fileBuffer[9] === 0x73 &&
    fileBuffer[10] === 0x6f &&
    fileBuffer[11] === 0x6d
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x20 &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x69 &&
    fileBuffer[9] === 0x73 &&
    fileBuffer[10] === 0x6f &&
    fileBuffer[11] === 0x32
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x1c &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x69 &&
    fileBuffer[9] === 0x73 &&
    fileBuffer[10] === 0x6f &&
    fileBuffer[11] === 0x6d
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x14 &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x69 &&
    fileBuffer[9] === 0x73 &&
    fileBuffer[10] === 0x6f &&
    fileBuffer[11] === 0x32
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x20 &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x69 &&
    fileBuffer[9] === 0x73 &&
    fileBuffer[10] === 0x6f &&
    fileBuffer[11] === 0x6d
  ) {
    fileType = 'mp4';
  } else if (
    fileBuffer[0] === 0x00 &&
    fileBuffer[1] === 0x00 &&
    fileBuffer[2] === 0x00 &&
    fileBuffer[3] === 0x1c &&
    fileBuffer[4] === 0x66 &&
    fileBuffer[5] === 0x74 &&
    fileBuffer[6] === 0x79 &&
    fileBuffer[7] === 0x70 &&
    fileBuffer[8] === 0x69 &&
    fileBuffer[9] === 0x73 &&
    fileBuffer[10] === 0x6f &&
    fileBuffer[11] === 0x32
  ) {
    fileType = 'mp4';
  }

  return fileType;
}
